In [1]:
#Importing the libraries
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

import warnings
warnings.filterwarnings('ignore')

Data Collection & Analysis

In [97]:
# loading the data from csv file to a Pandas DataFrame
df = pd.read_csv('C:/Users/heman/OneDrive/Desktop/Disease Prediction/dataset/covid19-dataset.csv')

In [98]:
df.head()

Dry_Cough  High_Fever  Sore_Throat  Difficulty_in_breathing  Outcome
0          0           2            3                        0        0
1         15          15           20                       16        1
2          4           5            0                        0        0
3          4           7            9                       10        0
4          0           0            1                        0        0

In [99]:
file_path = "C:/Users/heman/OneDrive/Desktop/Disease Prediction/dataset/covid19-dataset.csv"
df.to_csv(file_path, index=False)
df

Dry_Cough  High_Fever  Sore_Throat  Difficulty_in_breathing  Outcome
0           0           2            3                        0        0
1          15          15           20                       16        1
2           4           5            0                        0        0
3           4           7            9                       10        0
4           0           0            1                        0        0
5           6           0            6                        0        0
6          16          17           18                       16        1
7          17          17            0                        0        1
8           0          18            0                       18        1
9          16          15           18                       20        1
10          0           8            0                        0        0
11          7           8           10                        0        0
12          8           0            6                       10        0
13         15          17            0                       18        1
14          2           5            0                        0        0
15          5           0            1                        0        0
16          0          18           17                       13        1
17         17          18            0                        8        1
18          0          15            0                       16        1
19          7          18           12                       17        1
20          0           3            8                        0        0
21         20          16            0                        0        1
22         16           0            0                       19        1
23          0           0            1                        0        0
24         17           0            0                        0        0
25          0          10           16                       18        1
26          6           8            0                        0        0
27         14          16           17                        0        1
28         15           0            0                        0        0
29         20           0           18                        0        1
30          0          20           19                        0        1
31          8           8            0                        1        0
32         10           8            2                        0        0
33         12           0           18                        0        0
34         17          19           20                        0        1
35         12           0            0                        3        0
36         20          16            0                        2        1
37         16           4            0                       17        1
38          1           0            2                        0        0
39         14          20           16                        0        1
40          0           8            0                        0        0
41         19           0           20                        6        1
42         18           0           15                        2        1
43          0          10            0                        0        0
44         20          20           20                       20        1
45          0           5            5                        5        0
46          6           0            6                        0        0
47         19           0           19                       19        1

In [100]:
df.shape
df.describe()

Dry_Cough  High_Fever  Sore_Throat  Difficulty_in_breathing    Outcome
count  48.000000   48.000000    48.000000                48.000000  48.000000
mean    9.145833    8.208333     7.145833                 5.708333   0.500000
std     7.525813    7.537024     8.021221                 7.701777   0.505291
min     0.000000    0.000000     0.000000                 0.000000   0.000000
25%     0.000000    0.000000     0.000000                 0.000000   0.000000
50%     8.000000    8.000000     2.500000                 0.000000   0.500000
75%    16.000000   16.000000    16.250000                13.750000   1.000000
max    20.000000   20.000000    20.000000                20.000000   1.000000

In [101]:
df['Outcome'].value_counts()

Outcome
0    24
1    24
Name: count, dtype: int64

In [102]:
df.fillna(0)

Dry_Cough  High_Fever  Sore_Throat  Difficulty_in_breathing  Outcome
0           0           2            3                        0        0
1          15          15           20                       16        1
2           4           5            0                        0        0
3           4           7            9                       10        0
4           0           0            1                        0        0
5           6           0            6                        0        0
6          16          17           18                       16        1
7          17          17            0                        0        1
8           0          18            0                       18        1
9          16          15           18                       20        1
10          0           8            0                        0        0
11          7           8           10                        0        0
12          8           0            6                       10        0
13         15          17            0                       18        1
14          2           5            0                        0        0
15          5           0            1                        0        0
16          0          18           17                       13        1
17         17          18            0                        8        1
18          0          15            0                       16        1
19          7          18           12                       17        1
20          0           3            8                        0        0
21         20          16            0                        0        1
22         16           0            0                       19        1
23          0           0            1                        0        0
24         17           0            0                        0        0
25          0          10           16                       18        1
26          6           8            0                        0        0
27         14          16           17                        0        1
28         15           0            0                        0        0
29         20           0           18                        0        1
30          0          20           19                        0        1
31          8           8            0                        1        0
32         10           8            2                        0        0
33         12           0           18                        0        0
34         17          19           20                        0        1
35         12           0            0                        3        0
36         20          16            0                        2        1
37         16           4            0                       17        1
38          1           0            2                        0        0
39         14          20           16                        0        1
40          0           8            0                        0        0
41         19           0           20                        6        1
42         18           0           15                        2        1
43          0          10            0                        0        0
44         20          20           20                       20        1
45          0           5            5                        5        0
46          6           0            6                        0        0
47         19           0           19                       19        1

In [103]:
print(df.dtypes)

Dry_Cough                  int64
High_Fever                 int64
Sore_Throat                int64
Difficulty_in_breathing    int64
Outcome                    int64
dtype: object


In [104]:
df.groupby('Outcome').mean()

Dry_Cough  High_Fever  Sore_Throat  Difficulty_in_breathing
Outcome                                                             
0         5.125000    3.541667     3.250000                 1.208333
1        13.166667   12.875000    11.041667                10.208333

In [105]:
#Separating data & labels
X = df.drop(columns='Outcome', axis=1)
Y = df['Outcome']
print(X)

    Dry_Cough  High_Fever  Sore_Throat  Difficulty_in_breathing
0           0           2            3                        0
1          15          15           20                       16
2           4           5            0                        0
3           4           7            9                       10
4           0           0            1                        0
5           6           0            6                        0
6          16          17           18                       16
7          17          17            0                        0
8           0          18            0                       18
9          16          15           18                       20
10          0           8            0                        0
11          7           8           10                        0
12          8           0            6                       10
13         15          17            0                       18
14          2           5            0  

In [106]:
print(Y)

0     0
1     1
2     0
3     0
4     0
5     0
6     1
7     1
8     1
9     1
10    0
11    0
12    0
13    1
14    0
15    0
16    1
17    1
18    1
19    1
20    0
21    1
22    1
23    0
24    0
25    1
26    0
27    1
28    0
29    1
30    1
31    0
32    0
33    0
34    1
35    0
36    1
37    1
38    0
39    1
40    0
41    1
42    1
43    0
44    1
45    0
46    0
47    1
Name: Outcome, dtype: int64


Data Standardization 

In [107]:
scalar = StandardScaler()
Standardized_data = scalar.fit_transform(X)
print(Standardized_data)

[[-1.22812218 -0.83242822 -0.5223277  -0.7490142 ]
 [ 0.7861101   0.91064295  1.61947836  1.35041246]
 [-0.69099357 -0.43018102 -0.90029348 -0.7490142 ]
 [-0.69099357 -0.16201623  0.23360385  0.56312746]
 [-1.22812218 -1.10059301 -0.77430489 -0.7490142 ]
 [-0.42242927 -1.10059301 -0.14436193 -0.7490142 ]
 [ 0.92039225  1.17880774  1.36750117  1.35041246]
 [ 1.0546744   1.17880774 -0.90029348 -0.7490142 ]
 [-1.22812218  1.31289014 -0.90029348  1.61284079]
 [ 0.92039225  0.91064295  1.36750117  1.87526912]
 [-1.22812218 -0.02793383 -0.90029348 -0.7490142 ]
 [-0.28814712 -0.02793383  0.35959244 -0.7490142 ]
 [-0.15386497 -1.10059301 -0.14436193  0.56312746]
 [ 0.7861101   1.17880774 -0.90029348  1.61284079]
 [-0.95955788 -0.43018102 -0.90029348 -0.7490142 ]
 [-0.55671142 -1.10059301 -0.77430489 -0.7490142 ]
 [-1.22812218  1.31289014  1.24151258  0.95676996]
 [ 1.0546744   1.31289014 -0.90029348  0.30069913]
 [-1.22812218  0.91064295 -0.90029348  1.35041246]
 [-0.28814712  1.31289014  0.61

In [108]:
X = Standardized_data
Y = df['Outcome']

In [109]:
print(X)
print(Y)

[[-1.22812218 -0.83242822 -0.5223277  -0.7490142 ]
 [ 0.7861101   0.91064295  1.61947836  1.35041246]
 [-0.69099357 -0.43018102 -0.90029348 -0.7490142 ]
 [-0.69099357 -0.16201623  0.23360385  0.56312746]
 [-1.22812218 -1.10059301 -0.77430489 -0.7490142 ]
 [-0.42242927 -1.10059301 -0.14436193 -0.7490142 ]
 [ 0.92039225  1.17880774  1.36750117  1.35041246]
 [ 1.0546744   1.17880774 -0.90029348 -0.7490142 ]
 [-1.22812218  1.31289014 -0.90029348  1.61284079]
 [ 0.92039225  0.91064295  1.36750117  1.87526912]
 [-1.22812218 -0.02793383 -0.90029348 -0.7490142 ]
 [-0.28814712 -0.02793383  0.35959244 -0.7490142 ]
 [-0.15386497 -1.10059301 -0.14436193  0.56312746]
 [ 0.7861101   1.17880774 -0.90029348  1.61284079]
 [-0.95955788 -0.43018102 -0.90029348 -0.7490142 ]
 [-0.55671142 -1.10059301 -0.77430489 -0.7490142 ]
 [-1.22812218  1.31289014  1.24151258  0.95676996]
 [ 1.0546744   1.31289014 -0.90029348  0.30069913]
 [-1.22812218  0.91064295 -0.90029348  1.35041246]
 [-0.28814712  1.31289014  0.61

Train Test Spilt

In [110]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.2, stratify=Y, random_state=2)

In [111]:
print(X.shape, X_train.shape, X_test.shape)

(48, 4) (38, 4) (10, 4)


In [112]:
classifier = svm.SVC(kernel='linear')

In [113]:
#training the support vecti machine Classifier
classifier.fit(X_train, Y_train)

SVC(kernel='linear')

Model Evaluation

Accuracy Score

In [114]:
X_train_prediction = classifier.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)
print(training_data_accuracy)

0.9736842105263158


In [115]:
X_test_prediction = classifier.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)
print(test_data_accuracy)

1.0


Prediction System

In [116]:
input_data = (0,0,1,0)

#converting input array into numpy array
input_data_as_numpy_array = np.asarray(input_data)

#Reshape the array as we are predicting for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

std_data = scalar.transform(input_data_reshaped)
print(std_data)

prediction = classifier.predict(std_data)
print(prediction)

if (prediction[0] == 1):
  print('The person is affected with Covid-19')
else:
  print('The person is not affected with Covid-19')

[[-1.22812218 -1.10059301 -0.77430489 -0.7490142 ]]
[0]
The person is not affected with Covid-19


saving the trained model

In [117]:
import pickle
filename = 'C:/Users/heman/OneDrive/Desktop/Disease Prediction/saved_models/Covid19_model.sav'
pickle.dump(classifier, open(filename, 'wb'))
loaded_model = pickle.load(open('C:/Users/heman/OneDrive/Desktop/Disease Prediction/saved_models/Covid19_model.sav', 'rb'))